[versions]
appcompat = "1.6.1"
espressoCore = "3.5.1"
junitVersion = "1.1.5"
junit = "4.13.2"
constraintlayout = "2.1.4"
ktx = "1.9.0"
material = "1.9.0"
androidGradlePlugin = "8.1.1"
kotlin = "1.9.0"

[libraries]
android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }